### ISSUE TITLE
URI style refactoring - ProbBank

### ISSUE THREAD

**Issue by luigi-asprino** [framester/working-group#25]
This relates to #3

**Comment by alessandro-russo** [comment]
Please also define a URI mapping for local roles.

Take into account that a base URI like `https://w3id.org/framester/data/propbank-3.4/LocalRole/` is not enough. We need a URI scheme that allows distinguishing between e.g. the _writer_ of write-01 and the _writer_ of handwrite-01.

In the current data the name of the roleset is part of the URI:
- _writer_ of write-01: https://w3id.org/framester/pb/data/role/write-01/writer
- _writer_ of handwrite-01: https://w3id.org/framester/pb/data/role/handwrite-01/writer

**Comment by alessandro-russo** [comment]
Also consider [my comment](https://github.com/framester/working-group/issues/15#issuecomment-1560181462) in #15 for the URI mapping for the schema (`https://w3id.org/framester/ontology/propbank/` vs `https://w3id.org/framester/schema/propbank/`).

**Comment by luigi-asprino** [comment]
Hi @alessandro-russo 

> * _writer_ of write-01: https://w3id.org/framester/pb/data/role/write-01/writer
> * _writer_ of handwrite-01: https://w3id.org/framester/pb/data/role/handwrite-01/writer

As far as I understand “writer" is a kind of a "role" of the frame "write-01", right?
As this is similar to the FrameNet structure, we can apply a similar convention in which the local id of the frame element is 

<name_of_the_frame_element_>.<name_of_the_frame>

For example https://w3id.org/framester/framenet/abox/fe/Buyer.commerce_scenario

@vpresutti, WDYT?

**Comment by luigi-asprino** [comment]
Refactoring has been completed.

Input: Propbank 3.4.0
Mapping: RML
[Output](https://www.dropbox.com/scl/fi/jqeaycorkv0694z011z3l/propbank-amr-3.4.0-ttl.zip?rlkey=sdfkb9pod8m2t8qzn5w395yyb&dl=0)
