### ISSUE TITLE
URI style refactoring - VerbNet

### ISSUE THREAD

**Issue by luigi-asprino** [framester/working-group#28]
This relates to #3

**Comment by andreamust** [comment]
URI Style

Ontology:

`https://w3id.org/framester/ontology/verbnet/(class or property id)`

Resource:

`https://w3id.org/framester/resource/verbnet/(class name)/<resource id>`

**Comment by luigi-asprino** [comment]
Hi @andreamust,

Have you created the CSV?

**Comment by andreamust** [comment]
Here is the CSV file with the URI refactoring:

[verbnet_mappings.csv](https://github.com/framester/working-group/files/11556925/verbnet_mappings.csv)

**Comment by luigi-asprino** [comment]
Hi @andreamust,

Thanks for your mappings. I'm using them for refactoring the resource.
However, there are unmapped prefixes though.

This is the list of prefixes extracted with the [URI Engineer](https://github.com/framester/uri-engineer)

```
http://www.w3.org/1999/02/22-rdf-syntax-ns#
https://w3id.org/framester/framenet/abox/fe/
https://w3id.org/framester/framenet/abox/frame/
https://w3id.org/framester/wn/wn30/instances/
https://w3id.org/framester/vn/vn31/data/
http://www.w3.org/2000/01/rdf-schema#
https://w3id.org/framester/vn/schema/
http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#
https://w3id.org/framester/vn/vn31/data/vcprepositionselection/
http://www.w3.org/2004/02/skos/
https://w3id.org/framester/vn/vn31/data/prep/
http://www.w3.org/2002/07/owl#
https://w3id.org/framester/vn/vn31/data/vsprepositionselection/
http://www.w3.org/2004/02/skos/core#
http://www.ontologydesignpatterns.org/ont/d0.owl#
https://w3id.org/framester/pb/pbdata/
https://w3id.org/framester/schema/
```

Although many of them belong to other resources, there are a bunch which pertain verbnet.

```
https://w3id.org/framester/vn/vn31/data/
https://w3id.org/framester/vn/schema/
https://w3id.org/framester/vn/vn31/data/vcprepositionselection/
https://w3id.org/framester/vn/vn31/data/prep/
https://w3id.org/framester/vn/vn31/data/vsprepositionselection/
```
Could you please have a look at them and update the mappings?

**Comment by luigi-asprino** [comment]
The refactoring has been completed.

- Input: https://www.dropbox.com/scl/fi/grdnh3iwlrkd69cjw0nea/3.1.zip?rlkey=3ji63dj7ihcky70vc7t4l12tt&dl=0
- Software used for refactoring: https://github.com/framester/uri-engineer
The refactoring required manual intervention on the files:

	vcarg-fe-mapping.ttl
	vn2wn.ttl
	vsprepositionselection.ttl
	vnclass-frame-map.ttl
	predmatrix-verbsense-frames.ttl
	verbsense-frames-matching-based-fn_monosemous.ttl
	vnssel.ttl
	arg-fe-mapping-throughpredmatrix.ttl
	vnfnroleclosematch.ttl
	verbnet31sem.ttl
	semlink-verbsense-frames.ttl
	vsprepositionselection.ttl
	verbnet31args.ttl
	vn2wn.ttl

Still, prefixes of propbank frames in the file named vs-pb-predmatrix.ttl need to be refactored once propbank refactoring completes (#25)

- Prefix Mapping file: https://www.dropbox.com/scl/fi/5gb1qqy2pvguq8kzwvs6x/verbnet_mappings.csv?rlkey=d5ut0019j1cxxuvnxwqkbewd7&dl=0

- Output: https://www.dropbox.com/scl/fi/lumno2o4zgil8md0082oo/3.1.zip?rlkey=t2qvijh3ymgozoukt37bhfee7&dl=0

- SameAs: https://www.dropbox.com/scl/fi/bp0cs8j2zw505jn5v0w2z/sameAs-framester4.zip?rlkey=nu7t2142p587qcvxzpdi1juw8&dl=0
